### PR TITLE
one more file

### PR DESCRIPTION
**Pull request by nonopolarity**

### CODE REVIEW

**Comment by nonopolarity** [comment]
hm... markdown comments?

``` java
   for(int i=0 ; i < 5 ; i++)
   {
      System.out.println("i is : " + i);
   }
```

**Comment by nonopolarity** [comment]
so that was Java, now let's see JavaScript:

``` javascript
   for(int i=0 ; i < 5 ; i++)
   {
      System.out.println("i is : " + i);
   }
```

**Comment by nonopolarity** [comment]
This is marked as JavaScript:

``` javascript
function foo() {
   for(var i=0 ; i < 5 ; i++)
   {
      console.log("i is : " + i);
   }
}
```

**Comment by nonopolarity** [comment]
what if marked as Java:

This is marked as JavaScript:

``` java
function foo() {
   for(var i=0 ; i < 5 ; i++)
   {
      console.log("i is : " + i);
   }
}
```

**Comment by nonopolarity** [comment]
Here is Python:

``` python
def index(request):
    arr = [[x+y for x in [1,2,3,4]] for y in [10,100,1000]]
    s = json.dumps(arr, sort_keys=True, indent=4)
    return HttpResponse("<pre>Hello, world. You're at the polls index.\n" + s)
```

**Comment by nonopolarity** [comment]
How can you omit Ruby:

``` ruby
p [1,3,5].inject(:+)
arr = [1, 3, 5, 12].map {|i| i * i}.select{|i| i % 2 == 0}
p arr
```

**Comment by nonopolarity** [comment]
I :eyes: that :bug: and I :cold_sweat:.
:trophy: for :microscope: it.
:+1: and :sparkles: on this :ship:, it's :fire::poop:! :clap::tada::panda_face:

**Comment by jianlin** [comment]
:+1: :tada: :clap: :clap:

**Comment by jianlin** [comment]
:+1::tada::clap::clap:

**Pull request merged**
